// Code generated by scripts/generate-migration-manifest.ts. DO NOT EDIT.
//
// Run `npx tsx scripts/generate-migration-manifest.ts` after adding, removing
// or renaming a migration. `lib/migrations/manifest.test.ts` fails if this file
// and `migrations/` disagree, so drift cannot reach main.
//
// This exists so the startup check in `instrumentation.ts` knows which
// migrations the build expects without reading `migrations/` — the runtime
// image does not contain that directory. Names are filenames minus the `.ts`
// extension, which is exactly what kysely records in its migration table.

export const MIGRATION_MANIFEST: readonly string[] = [
  "1731802396765_create-table-suggested-props",
  "1731936096261_create-view-v-suggested-props",
  "1732111393592_create-table-feature-flags",
  "1732464326543_alter-props-table-add-notes-col",
  "1732668557408_create-table-password-resets",
  "1732848043401_fix-nullable-columns",
  "1732982569359_add-id-columns-vforecasts",
  "1732991808870_remove-flag-2025-fcasts",
  "1732993480596_create-table-invite-secrets",
  "1733071132579_alter-logins-table-remove-salt-col",
  "1734929073136_alter-forecasts-table-make-uniq-constraint",
  "1742766120188_alter-invite-tokens-table-add-notes-column",
  "1742860456350_alter-resolutions-table-add-notes-column",
  "1742986038982_add-flag-personal-props",
  "1742986338172_alter-props-table-add-user-id-column",
  "1742987477096_enable-rls-on-props-table",
  "1743086893944_alter-resolutions-table-add-user-id-column",
  "1743087634287_enable-rls-on-resolutions-table",
  "1743088073468_set-security-barrier-and-invoker-on-views",
  "1743287501033_create-table-competitions",
  "1743531229852_alter-table-props-make-category-nullable",
  "1743559965925_alter-tables-add-updated-at-and-created-at-columns",
  "1743562246323_enable-rls-on-forecasts-table",
  "1744081605619_add-time-columns-v-forecasts",
  "1757770670355_alter-competitions-add-visible",
  "1757857228511_add-deactivated-at-to-users",
  "1761789015144_alter-table-competitions-rename-forecast-date-columns",
  "1764132153397_alter-competitions-remove-visible",
  "1768298817000_add-idp-user-id",
  "1768376738912_complete-idp-migration",
  "1768466662120_enable-rls-on-users-and-suggested-props",
  "1768587655070_add-username-to-users",
  "1768992592533_add-picture-url-to-users",
  "1769364781813_private_competitions_schema",
  "1769364811701_private_competitions_rls_views",
  "1773516227456_add-picture-url-to-competition-members-view",
  "1773712944723_relax-prop-category-constraint",
  "1788220800000_add-choice-props",
  "1788307200000_fail-closed-private-competition-rls",
  "1788393600000_unique-idp-user-id",
];
